### ISSUE TITLE
Installer Error

### ISSUE THREAD

**Issue by arcabaran** [Lauriethefish/Quest-Discord-Presence#1]
Hello, I've ran into an issue with the Windows installation client. Below, this is the screen that first appears, where I select to automatically close the applications:
![image](https://user-images.githubusercontent.com/32419867/104819256-4d954200-57fa-11eb-89c4-42b35779126f.png)
However, afterward, this error repeatedly occurs and it doesn't appear that there's a way to stop it and thus get the program to work the way it was intended and include song name, difficulty etc.
![image](https://user-images.githubusercontent.com/32419867/104819288-7fa6a400-57fa-11eb-99ce-3599f4e79591.png)
Is this a known issue and is there a fix? Thanks!

**Comment by Lauriethefish** [comment]
The issue is caused by the installer not having administrator permissions.
To get around it, close the installer, then manually kill the client in task manager first.
Then open the installer again.

Alternatively, run the installer as administrator.
Please reopen if this doesn't fix the issue.

**Comment by arcabaran** [comment]
This fixed the issue, thank you.
