### ISSUE TITLE
Issue With Client

### ISSUE THREAD

**Issue by arcabaran** [Lauriethefish/Quest-Discord-Presence#2]
![image](https://user-images.githubusercontent.com/32419867/104829484-6cb7c200-5842-11eb-8b7b-37f91b2ac620.png)
As shown above, regardless of me using the client with the correct IP and Beat Saber being open and my Quest 2 being on, the client states that it could not reach my Quest and the status only shows the following. Help would be appreciated. :)

**Comment by Lauriethefish** [comment]
Try restarting Discord and your PC.
Also, install ModList to make sure that the mod is loading ingame.

**Comment by Lauriethefish** [comment]
I will close this due to no response for two weeks.
