### ISSUE TITLE
Crashes when selecting a song

### ISSUE THREAD

**Issue by trevorsmithy** [Lauriethefish/Quest-Discord-Presence#3]
Every time I click any song in the menu, it immediately crashes Beat Saber.
Disabling just this mod fixed the issue.
(Note: It was properly showing "Beat Saber: In the Menu" on Discord before I clicked a song.)

**Comment by Lauriethefish** [comment]
I need a log file for more information. (this doesn't happen to me so I have no idea)
Instructions for getting one are below.

**1)** Copy and paste the following into your file browser's address bar:
`%appdata%\SideQuest\platform-tools`
Make sure that you have a file named adb or adb.exe
**2)** Hold shift, and while holding, right click somewhere blank in that folder
**3)** Click 'Open command prompt' or 'Open PowerShell' 
**4)** Connect your Quest to your computer
**5)** Write `.\adb.exe logcat > logcat.log` in that command line window that was opened and press enter 
Leave that window opened, and start the game on the Quest (while it is connected to your PC)
**6)** Then, play/fail a song, or any other thing that you need to get a log for, and take off your Quest
**7)** You can now close the command line window that you opened before
**8)** A file named `logcat.log` will be in the folder you opened first
**9)** Drag and drop that file into Discord to upload the log file

**Comment by trevorsmithy** [comment]
Here is the log
[logcat.log](https://github.com/Lauriethefish/Quest-Discord-Presence/files/5937545/logcat.log)

**Comment by Lauriethefish** [comment]
The log doesn't contain a valid crash, so I don't know what to do here.
I have asked for another log, but none has been sent, so I will close this issue due to lack of info.
If you have another log, please DM it to me on discord @Lauriethefish#6700 and I can reopen this issue.
