### ISSUE TITLE
Discord reports 5 Hours elapsed when in any menu

### ISSUE THREAD

**Issue by ovandermeer** [Lauriethefish/Quest-Discord-Presence#4]
Whenever I boot the game, Discord reports that I have elapsed 5 hours in the menu. This happens when I start the game, or whenever I leave any song and return to the menu. The time still properly increments, but it looks like the client is adding 5 hours to my playtime for some reason. I have not left my Quest on to see if it increments beyond the one hour mark.

![image](https://user-images.githubusercontent.com/20265591/107303582-57067880-6a4d-11eb-9882-9d4ec22a35bb.png)

**Comment by Lauriethefish** [comment]
Fixed by a client change that I'll release shortly. This is a timezone related issue.

**Comment by Lauriethefish** [comment]
Fix released
