### ISSUE TITLE
Doest work

### ISSUE THREAD

**Issue by ByQuartz** [Lauriethefish/Quest-Discord-Presence#5]
Hey,
Im pretty sure that i Install everything correctly but it will not work do you have an Idea why?

**Comment by Lauriethefish** [comment]
I need further information. What _exactly_ doesn't work like you think it should?

**Comment by ByQuartz** [comment]
I the connection from my quest to Pc with your tool,
WHEN I IPEN THE TOOL TYPE IN THE RIGHT IP from my Quest and then press Connect it says it can't find or something like that. And yes I have Beatsaber open when I click connect.
So do you have an idea?

**Comment by Lauriethefish** [comment]
Do you definitely have the Beat Saber mod installed? If you think you do, please install my ModList mod and check that it's actually loading correctly.

**Comment by ByQuartz** [comment]
Ok let me check give me some minutes

**Comment by ByQuartz** [comment]
I don't know why but it's working now
